sudo: required
dist: trusty

language: julia

os:
  - linux

julia:
  - 0.5
  - 0.6
  - nightly

addons:
  apt:
    packages:
      - gfortran
      - libblas-dev

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("AMVW"); Pkg.test("AMVW"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("AMVW")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
