language: julia

os:
  - linux

julia:
  - 1.0
  - 1.4
  - nightly

addons:
  apt:
    packages:
      - gfortran
      - libblas-dev

after_success:
- julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'